
services:
  jena-fuseki:
    image: stain/jena-fuseki:latest
    volumes:
      - fuseki-data:/fuseki
    ports:
      - 3030:3030
    environment:
      - JVM_ARGS=-Xmx2G
      - ADMIN_PASSWORD=EuTKAcHp0dpeQbJ
    
volumes:
  fuseki-data: