# SELECT (COUNT(*) AS ?count)
#   FROM <./dataset/2024_medalists_nuts_only.csv#encoding=utf-8;header=present;delimiter=comma>
#   WHERE {}

PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbp: <https://dbpedia.org/property/>
PREFIX dbpage: <https://dbpedia.org/page/>
PREFIX ex: <http://example.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos>

CONSTRUCT {
    ?medalist_id rdfs:seeAlso       ?medalist_link;
                rdf:type            foaf:Person;
                foaf:name           ?medalist_name;
                dbo:birthDate       ?date_of_birth_typed;
                foaf:gender         ?sex_or_gender;
                dbo:birthPlace      ?place_of_birth_id;
                ex:delegation       ?delegation_id.

    ?place_of_birth_id      foaf:name        ?place_of_birth;
                            # type:place
                            geo:lat          ?lat_typed;
                            geo:long          ?lon_typed;
                            ex:nut0_id      ?nuts0_id_uri;
                            ex:nut0_name    ?nuts0_name;
                            ex:nut1_id      ?nuts1_id_uri;
                            ex:nut1_name    ?nuts1_name;
                            ex:nut2_id      ?nuts2_id_uri;
                            ex:nut2_name    ?nuts2_name;
                            ex:nut2_population  ?nuts2_population_typed;
                            ex:nut2_gdp     ?nuts2_gdp_typed; # Will be missing if NA
                            ex:nut3_id      ?nuts3_id_uri;
                            ex:nut3_name    ?nuts3_name;
                            ex:nut3_population  ?nuts3_population_typed;
                            ex:nut3_gdp     ?nuts3_gdp_typed. # Will be missing if NA


    ?delegation_id      rdfs:seeAlso    ?delegation_link;
                        foaf:name       ?delegation_name.

    ?country_medal_id   foaf:name       ?country_medal;
                        # type: country 
                        dbpage:ISO_3166-1_alpha-2   ?country_medal_code2;
                        dbpage:ISO_3166-1_alpha-3   ?country_medal_code3.
}
FROM <file:./dataset/2024_medalists_nuts_only.csv#encoding=utf-8;header=present;delimiter=comma>
WHERE {
    # Medalist
    BIND (URI(CONCAT("https://www.wikidata.org/wiki/", ?medalist_wikidata_id)) AS ?medalist_id).
    BIND (xsd:date(?date_of_birth) AS ?date_of_birth_typed).

    # Place of birth
    BIND (URI(CONCAT("https://www.wikidata.org/wiki/", ?place_of_birth_wikidata_id)) AS ?place_of_birth_id).
    # Latitude and longitude
    BIND (xsd:float(?lat) AS ?lat_typed).
    BIND (xsd:float(?lon) AS ?lon_typed).
    # Nuts
    BIND (URI(CONCAT("http://data.europa.eu/nuts/code/", ?nuts0_id)) AS ?nuts0_id_uri).
    BIND (URI(CONCAT("http://data.europa.eu/nuts/code/", ?nuts1_id)) AS ?nuts1_id_uri).
    BIND (URI(CONCAT("http://data.europa.eu/nuts/code/", ?nuts2_id)) AS ?nuts2_id_uri).
    BIND (URI(CONCAT("http://data.europa.eu/nuts/code/", ?nuts3_id)) AS ?nuts3_id_uri).
    BIND (xsd:int(?nuts2_population) AS ?nuts2_population_typed).
    BIND (xsd:float(?nuts2_gdp) AS ?nuts2_gdp_typed).   # If NA will be dropped
    BIND (xsd:int(?nuts3_population) AS ?nuts3_population_typed).
    BIND (xsd:float(?nuts3_gdp) AS ?nuts3_gdp_typed).   # If NA will be dropped

    # Delegation
     BIND (URI(CONCAT("https://www.wikidata.org/wiki/", ?delegation_wikidata_id)) AS ?delegation_id).

    # Country
    BIND (URI(CONCAT("https://www.wikidata.org/wiki/", ?country_medal_wikidata_id)) AS ?country_medal_id).
}

# medalist_link	https://en.wikipedia.org/wiki/Nicolas_Gestin
# medalist_name	Nicolas Gestin
# medal	gold

# CONSTRUCT {
#     ?measure    ex:declarativeAirport   ?airport;
#                 dbo:year               ?year_int;
#                 rdf:value               ?value;
#                 ex:unit                 ?unit;
#                 ex:measuredMetric       ?tra_meas;
#                 ex:coverageTransport    ?tra_cov;
#                 ex:airline              ?airline;
#                 rdf:type                ex:AirportMetricValue.

#     #   Each rep_airp attributes is transformed into an airport individual
#     ?airport    dbo:iso31661Code            ?countryCode;       #   ISO31661-1 ALPHA 2
#                 dbo:icaoLocationIdentifier  ?icaoID;            #   ICAO - 4 LETTERS ID
#                 rdf:type                    dbo:Airport.
# }
# FROM <file:../data/avia_tf_ala_linear.csv#encoding=utf-8;header=present;delimiter=comma>
# WHERE {

#     BIND (xsd:integer(?TIME_PERIOD) AS ?year_int).
#     #   Useful to have both float and int values in our resulting file
#     BIND (IF (?unit = "T",
#         xsd:float(?OBS_VALUE),
#         xsd:integer(?OBS_VALUE)) AS ?value).
    
#     #   To get countryCode and icaoID from the rep_airp attribute
#     BIND (SUBSTR(STR(?rep_airp), 1, 2) AS ?countryCode).
#     BIND (SUBSTR(STR(?rep_airp), 4, 4) AS ?icaoID).

#     BIND (URI(CONCAT("http://example.org/measure/", STR(?countryCode) ,"/", STR(?icaoID), "/", STR(?TIME_PERIOD), "/", STR(?tra_meas), "/", STR(?tra_cov), "/", STR(?airline))) AS ?measure).
#     BIND (URI(CONCAT("http://example.org/airport/", STR(?countryCode) ,"/", STR(?icaoID))) AS ?airport).

#     FILTER(?freq="A")
# }
